# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /html-javascript-css/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /html-javascript-scss/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /html-typescript-css/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /html-typescript-scss/
    schedule:
      interval: daily
