name: build
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ 'html-javascript-css', 'html-javascript-scss', 'html-typescript-css', 'html-typescript-scss' ]
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ matrix.directory }}
    name: ビルド(${{ matrix.directory }})
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
      - name: Node.jsセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: 依存関係をインストール
        run: npm ci
      - name: ビルド
        run: npm run build
 
