name: release-gh-pages
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: ビルド(html-javascript-css)
        working-directory: ./html-javascript-css
        run: |
          npm ci
          ./node_modules/.bin/vite build --base=/vite-project-sample/html-javascript-css/ --outDir='../docs/html-javascript-css/'
      - name: ビルド(html-javascript-scss)
        working-directory: ./html-javascript-scss
        run: |
          npm ci
          ./node_modules/.bin/vite build --base=/vite-project-sample/html-javascript-scss/ --outDir='../docs/html-javascript-scss/'
      - name: ビルド(html-typescript-css)
        working-directory: ./html-typescript-css
        run: |
          npm ci
          ./node_modules/.bin/vite build --base=/vite-project-sample/html-typescript-css/ --outDir='../docs/html-typescript-css/'
      - name: ビルド(html-typescript-scss)
        working-directory: ./html-typescript-scss
        run: |
          npm ci
          ./node_modules/.bin/vite build --base=/vite-project-sample/html-typescript-scss/ --outDir='../docs/html-typescript-scss/'
      - name: ビルド(vue2)
        working-directory: ./vue2
        run: |
          npm ci
          ./node_modules/.bin/vite build --base=/vite-project-sample/vue2/ --outDir='../docs/vue2/'
      - name: ビルド(vue3)
        working-directory: ./vue3
        run: |
          npm ci
          ./node_modules/.bin/vite build --base=/vite-project-sample/vue3/ --outDir='../docs/vue3/'
      - name: gh-pagesブランチを更新
        run: |
          git --version
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch -a
          git checkout -b gh-pages
          git add --all
          git commit -a -m "npm run build-docs"
          git push --force origin gh-pages
